# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Publish debug build

on:
  push:
    paths:
      - "**.cs"
      - ".github/workflows/dotnet.yml"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Publish Debug
      run: dotnet publish -c Debug -r linux-arm64
    - name: Archive Debug Build Artifact (AzzyBot)
      uses: actions/upload-artifact@v4
      with:
        name: debug-artifact
        path: ./artifacts/publish/AzzyBot/debug_linux-arm64/*
